### ISSUE TITLE
When i change the host and send Save folder to my friend he cant see save to host

### ISSUE THREAD

**Issue by antoniohbmonteiro** [tfitz237/stardew-mp-save-editor#24]
My friend cant see the save to host when i send save to him

Maybe because file SaveGameInfo is not generated?

**Comment by tfitz237** [comment]
Hi @antoniohbmonteiro 

If you send the full directory of your modified save file to your friend, and open the saved game in SD that shows YOU as the host, the next time it is open (or saved I can't remember which) it will generate a new directory for the new host, a new SaveGameInfo, and a new filename based on the name of the host. 


Please let me know if this works as expected.
